# Generated by Django 4.2.9 on 2024-03-16 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('times_rented', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('status_of_renting', models.BooleanField(default=False)),
                ('user_preference', models.IntegerField(choices=[(1, 'Family'), (2, 'Bachelor'), (3, 'Students'), (4, 'Only_for_Girls'), (5, 'Only_for_Boys'), (6, 'all')], default=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
