# Generated by Django 4.2.9 on 2024-03-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_price_alter_property_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
