# Generated by Django 4.2.9 on 2024-03-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_pricing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='status_of_renting',
            new_name='availabality',
        ),
    ]
