# Generated by Django 4.2.9 on 2024-03-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_rename_status_of_renting_property_availabality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='default_document',
            field=models.FileField(upload_to='media/property_documents'),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='document2',
            field=models.FileField(blank=True, null=True, upload_to='media/property_documents'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='default_image',
            field=models.ImageField(upload_to='media/property_images'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/property_images'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/property_images'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/property_images'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/property_images'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='default_video',
            field=models.FileField(upload_to='media/property_videos'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='media/property_videos'),
        ),
    ]
