# Generated by Django 4.2.9 on 2024-03-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_propertydocument_default_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='type',
            new_name='price_type',
        ),
        migrations.RenameField(
            model_name='typeofproperty',
            old_name='type',
            new_name='property_type',
        ),
    ]
