# Generated by Django 4.2.9 on 2024-03-29 11:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0007_alter_property_availabality'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='current_renter',
            new_name='currentrenter',
        ),
    ]
