# Generated by Django 4.2.9 on 2024-03-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_was_cancled_alter_transaction_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Succes'), (2, 'Failure'), (3, 'Pending'), (4, 'Cancled')], default=3),
        ),
    ]
