# Generated by Django 4.2.9 on 2024-03-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Succes'), (2, 'Failure'), (3, 'Pending'), (4, 'Cancled')], default=1),
        ),
    ]
