# Generated by Django 4.2.9 on 2024-03-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_gender_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Service_User'), (2, 'Service_Partner')], default=1),
        ),
    ]
